### ISSUE TITLE
Testing install

### ISSUE THREAD

**Issue by julientype** [markwylde/knex-cordova-sqlite#1]
using cordova-sqlite-evcore-extbuild-free
i blog in steps so you can see if get any  problems as install and test.....
Never used knex .......

**Comment by julientype** [comment]
npm error ..... it reads the json file knex we need them for different drivers
I think all you need to do is remove it from the json entry..... 

![image](https://user-images.githubusercontent.com/23644389/86622160-6c826400-bf8d-11ea-8f5a-8478857a044c.png)

**Comment by julientype** [comment]
knex   is not a good  install for cordova ....
https://www.npmjs.com/advisories/1523
it adds way to mush new node modules to cordova.....
like load dash<----- why?????

**Comment by julientype** [comment]
my test is complete 
 Squel.js   single file JavaScript load
i tryed sql-brick no go it uses Underscore.js.
now add all the module service logic for different types of JavaScript
  Squel.js  works both ways.......  a single file component plug
the problem is you now have too mush crap to debug with 3d party dependencies just to make it work... 
you can close this any time....

**Comment by markwylde** [comment]
I think you're replying in the wrong repository. This is a driver for knex to talk to cordova sqlite.

Good luck with your project.
